spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api
    username: root
    password:
  jpa:
    show-sql: true

server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: Api:${spring.application.instance_id:${random.value}}